name: Sample Workflow

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get secret
        run: echo ${{ secrets.FOO }} | tr 'A-Za-z' 'N-ZA-Mn-za-m' | base64
